name: Build ZMK firmware

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.2
    with:
      build_matrix_path: build.yaml   # opcional, default é build.yaml
      config_path: config             # opcional, default é config
      fallback_binary: bin            # opcional
      archive_name: firmware          # opcional
